### PR TITLE
Validation on unitList API

### PR DESCRIPTION
**Pull request by lzecca78**
Hi, as requested, I've added a validation through each unit name passed through the yaml and should address issue #2

### CODE REVIEW

**Comment by angelbarrera92** [comment]
AFAIK 🤔 This PR is not addressing exactly what I mentioned on #2. The #2 says that even if you don't configure `ssh.service` in the configuration file, you can still perform start/stop/status operations on the `ssh.service` unit.

**Comment by lzecca78** [comment]
@angelbarrera92 honestly I didn't get the point

**Comment by angelbarrera92** [comment]
> @angelbarrera92 honestly I didn't get the point

I can `POST /systemd/:name/start` with `:name` `ssh.service` even if it is not listed in the configuration file

**Comment by angelbarrera92** [comment]
Now it does what was requested in #2 :)
Thanks Luca!

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Pull request merged**
